services:
  couch:
    image: couchdb:3.3.3
    volumes:
      - couchdb:/opt/couchdb/data
      - ./couch_locald:/opt/couchdb/etc/local.d
      - ./couch_certs:/opt/couchdb/cert
    ports:
      - 5984:5984
      - 6984:6984
volumes:
  couchdb: